spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.web.resources.add-mappings=true
server.port=8081

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ims
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Format SQL (optional)
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#app.storage.base-dir=D:/User/IMS/Springboot_Intern_Management_System/src/main/resources/static/files/Intern Docs/
#app.storage.base-dir2=D:/User/IMS/Springboot_Intern_Management_System/src/main/resources/static/files/Group Docs/

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youremail
spring.mail.password=password (As per 'Guide.txt')
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.session.timeout=3600s