spring.thymeleaf.cache=false
spring.thymeleaf.suffix=.html
spring.web.resources.add-mappings=true
server.port=${PORT}

spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=${LOCAL_DB_URL}
#spring.datasource.username=${LOCAL_DB_USERNAME}
#spring.datasource.password=${LOCAL_DB_PASSWORD}

spring.datasource.url=${AIVEN_DB_URL}
spring.datasource.username=${AIVEN_DB_USERNAME}
spring.datasource.password=${AIVEN_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.storage.base-dir=D:/Serious Projects/Springboot_Intern_Management_System/src/main/resources/static/files/Intern Docs/
app.storage.base-dir2=D:/Serious Projects/Springboot_Intern_Management_System/src/main/resources/static/files/Group Docs/

spring.mail.host=smtp.gmail.com
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.servlet.session.timeout=3600s

super_admin.default.email=${SUPER_ADMIN_EMAIL}
super_admin.default.password=${SUPER_ADMIN_PASSWORD}